---
title: "Difference in Differences"
number-sections: true
format:
  html:
    toc: true
    toc-location: left
    theme: default
    embed-resources: true
---

# Data simulation


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(did)
library(ggplot2)
set.seed(1234)

impact <- 200
n_group <- 10

time_points_base <- c(0, 1)
n <- length(time_points_base)
seasonality_base <- -cos(time_points_base/(2*pi))

time_points <- rep(time_points_base, 2*n_group)
seasonality <- rep(seasonality_base, 2*n_group)
D <- c(rep(0, 2*n_group), rep(1, 2*n_group))
id <- sort(rep(1:(2*n_group), 2))

Y_0 <- 500 + 200*D + 100*seasonality + rnorm(4*n_group, sd=100)
Y_1 <- Y_0 + D*time_points*impact
Y <- D*Y_1 + (1-D)*Y_0

df_observed <- data.frame(
  id, time_points, D, Y
)
```

# Plots

```{r}
df_all <- data.frame(
  id, time_points, D, seasonality, Y_0, Y_1, Y
)

res_plot <- ggplot(df_observed, aes(time_points, Y, color=as.factor(D))) +
  geom_point(aes(shape=as.factor(D))) +
  geom_smooth(method=lm, se=TRUE) +
  scale_colour_discrete(guide = "none") + 
  guides(shape=guide_legend(title="D")) +
  ylab('Number of views') 
  
# ggsave('ch11-dids_observed.png', res_plot)
res_plot
```


```{r}
res_plot <- ggplot(df_all, aes(time_points, color=as.factor(D), shape=as.factor(D))) +
  geom_point(aes(y=Y_0), shape=1) +
  geom_point(aes(y=Y_1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  guides(shape=guide_legend(title="D")) +
  ylab('Number of views') +
  stat_summary(
    aes(time_points, Y_0, group=as.factor(D)),
    geom = "point",
    fun.y = "mean",
    col = "black",
    shape=1
  ) +
  scale_colour_discrete(guide = "none") + 
  stat_summary(
    aes(time_points, Y_1, group=as.factor(D)),
    geom = "point",
    fun.y = "mean",
    col = "black"
  )

# ggsave('images/ch11-dids_terms.png', res_plot)
res_plot
```



```{r}
res_plot <- ggplot(df_all, aes(time_points, color=as.factor(D), shape=as.factor(D))) +
  geom_jitter(aes(y=Y_0), shape=1, width = 0.01) +
  geom_smooth(aes(y=Y_0), method=lm, linetype="dashed", se=FALSE) +
  geom_jitter(aes(y=Y_1), width = 0.01) +
  scale_shape_manual(values=c(17, 19)) +
  scale_colour_discrete(guide = "none") + 
  geom_smooth(aes(y=Y_1), method=lm, linetype="solid", se=FALSE) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  guides(shape=guide_legend(title="D")) +
  ylab('Number of views') 

# ggsave('ch11-dids_counterfactual.png', res_plot)
res_plot
```

```{r}
res_plot <- ggplot(df_all, aes(time_points, color=as.factor(D))) +
  geom_point(aes(y=Y_1), alpha= 0) +
  geom_smooth(aes(y=Y_0), method=lm, linetype="dashed", se=FALSE) +
  geom_smooth(aes(y=Y_1), method=lm, linetype="solid", se=FALSE) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  guides(color=guide_legend(title="D")) +
  ylab('Number of views')

# ggsave('ch11-dids_atet.png', res_plot)
res_plot
```

# DiD ATET estimation with the direct method

```{r}
diff_1 <- mean(df_observed[
  df_observed$time_points == 1 & df_observed$D == 1, 'Y'
]) - mean(df_observed[
  df_observed$time_points == 0 & df_observed$D == 1, 'Y'
])

diff_0 <- mean(df_observed[
  df_observed$time_points == 1 & df_observed$D == 0, 'Y'
]) -mean(df_observed[
  df_observed$time_points == 0 & df_observed$D == 0, 'Y'
])

diff_1 - diff_0
```


# DiD ATET with linear models

```{r}
model <- lm(Y~D*time_points, data=df_observed)
print(summary(model))
confint(model, level = 0.95) 
```

# DiD ATET with linear models with additional covariates

```{r}
n_a <- floor(n_group/4)
A <- c(rep(1, n_a*2), rep(0, 2*(n_group - n_a)))
n_a <- floor(n_group/2)
A <- c(A, rep(1, n_a*2), rep(0, 2*(n_group - n_a)))

D <- c(rep(0, 2*n_group), rep(1, 2*n_group))

Y_0_age <- Y_0 - 50 * A
Y_1_age <- Y_1 - 50 * A
Y_age <- D*Y_1_age + (1-D)*Y_0_age

df_observed_age <- data.frame(
  id, time_points, D, Y=Y_age, A
)

model <- lm(Y~D*time_points + A, data=df_observed_age)
print(summary(model))
confint(model, level = 0.95) 
```

# DiD ATET with the did package

```{r}
att_gt(
  yname='Y', tname = 'time_points', idname = 'id', gname = 'D',
  data = df_observed)
```