---
title: "Finding the difference between the S-learner and the T-learner"
number-sections: true
format:
  html:
    toc: true
    toc-location: left
    theme: default
    embed-resources: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

```{r}
library(rpart)
set.seed(12345)

n <- 20
maxdepth <- 5
b_z_x <- 5
b_z_y <- 5
b_x_y <- 2
sd <- 1
```


# Generate the data
```{r}
z <- rnorm(n, sd = sd)
x <- as.numeric(runif(n) < 1 / (1 + exp(-b_z_x * z)))
y <- b_z_y * z + b_x_y * x + rnorm(n, sd = sd)
df <- data.frame(z, x, y)
```


# Calculate the difference between groups of outcome y
```{r}
mean(df[df$x == 1, ]$y) - mean(df[df$x == 0, ]$y)
```


# S-learner
```{r}
model <- rpart(y ~ .,
    data = df,
    control = rpart.control(maxdepth = maxdepth, minsplit = 2, cp = 0)
)

df_do_0 <- df
df_do_0$x <- 0
predictions_0 <- predict(model, df_do_0)

df_do_1 <- df
df_do_1$x <- 1
predictions_1 <- predict(model, df_do_1)

print("ATE")
print(mean(predictions_1 - predictions_0))
print(predictions_1 - predictions_0)
```


# T-Learner
```{r}
df_0 <- df[df$x == 0, ]
df_1 <- df[df$x == 1, ]

model_0 <- rpart(y ~ .,
    data = df_0,
    control = rpart.control(maxdepth = maxdepth, minsplit = 2, cp = 0)
)

model_1 <- rpart(y ~ .,
    data = df_1,
    control = rpart.control(maxdepth = maxdepth, minsplit = 2, cp = 0)
)

predictions_0 <- predict(model_0, df)
predictions_1 <- predict(model_1, df)

print("ATE")
print(mean(predictions_1 - predictions_0))
print(predictions_1 - predictions_0)
```

